{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflight.sa" . }}
  labels:
    {{- include "kubeflight.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.liveCluster.enabled }}
{{- end }}
