apiVersion: v1
kind: Service
metadata:
  name: kubeflight
  namespace: kubeflight
  labels: {app.kubernetes.io/name: kubeflight}
spec:
  selector: {app.kubernetes.io/name: kubeflight}
  ports: [{name: http, port: 80, targetPort: http}]
